name: yandex
base: core18
version: '1.2'
summary: Browser from Yandex "LLC"
description: >
  A Russian based browser system that includes marketing utilities, navigational systems,
  metrical analytical advertising tools, and the famous AI voice control system "Alisa".

parts:
  browser:
    plugin: nil
    stage-packages: 
      - yandex

package-repositories:
  - type: apt
    components: [main]
    suites: [beta]
    key-id: 224974db7fed6decb7d855ef60b9cd3a083a7a9a
    url: http://repo.yandex.ru/yandex-browser/deb
