name: yandex-browser 
base: core20 
version: 1.2+git 
summary: Single-line elevator pitch for your amazing snap 
description: 
A Russian based browser system that includes marketing utilities, navigational systems, metrical analytical advertising tools, and the famous AI voice control system Alisa.

grade: stable 
confinement: strict 

parts:
  my-part:
    plugin: snapcraft plugins
